# Generated by Django 4.1.2 on 2022-10-31 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0002_products_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='items',
            field=models.ManyToManyField(to='App.products'),
        ),
    ]
