# Generated by Django 4.1.2 on 2022-11-04 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0003_recipe_items'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='items',
        ),
        migrations.AddField(
            model_name='recipe',
            name='ingredient1',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='recipe',
            name='ingredient2',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='recipe',
            name='ingredient3',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='recipe',
            name='quantity1',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='recipe',
            name='quantity2',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='recipe',
            name='quantity3',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='products',
            name='owned',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='products',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
    ]
