# Generated by Django 4.1.2 on 2022-12-11 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0005_alter_recipe_description_alter_recipe_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='description',
            field=models.TextField(default='Lorem ipsum'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='tags',
            field=models.JSONField(default=['breakfast/lunch/dinner', 'dietetic/greasy', 'easy/medium/hard', 'vegetarian/vegan']),
        ),
    ]
