# Generated by Django 4.1.2 on 2022-11-04 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0005_products_recipes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='ingredient1',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='ingredient2',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='ingredient3',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='quantity1',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='quantity2',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='quantity3',
        ),
        migrations.AddField(
            model_name='recipe',
            name='description',
            field=models.TextField(default='DUPA'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
