# Generated by Django 4.1.2 on 2022-11-07 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0006_remove_recipe_ingredient1_remove_recipe_ingredient2_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductsNonQuan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('owned', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='ProductsQuan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('quantity', models.IntegerField(default=0)),
            ],
        ),
        migrations.AlterField(
            model_name='recipe',
            name='description',
            field=models.TextField(default='nic'),
        ),
        migrations.DeleteModel(
            name='Products',
        ),
        migrations.AddField(
            model_name='productsquan',
            name='recipes',
            field=models.ManyToManyField(to='App.recipe'),
        ),
        migrations.AddField(
            model_name='productsnonquan',
            name='recipes',
            field=models.ManyToManyField(to='App.recipe'),
        ),
    ]
