# Generated by Django 4.1.2 on 2022-11-18 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0007_productsnonquan_productsquan_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productsnonquan',
            name='recipes',
        ),
        migrations.RemoveField(
            model_name='productsquan',
            name='recipes',
        ),
        migrations.AddField(
            model_name='recipe',
            name='products',
            field=models.ManyToManyField(to='App.productsquan'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='products_non',
            field=models.ManyToManyField(to='App.productsnonquan'),
        ),
    ]
